CREATE TABLE IF NOT EXISTS client (
id BIGINT AUTO_INCREMENT NOT NULL,
name VARCHAR(200) NOT NULL,
CONSTRAINT client_pk PRIMARY KEY (id),
CONSTRAINT client_check CHECK (LENGTH(name) >= 3)
);

CREATE TABLE IF NOT EXISTS planet (
id VARCHAR(100) NOT NULL,
name VARCHAR(500) NOT NULL,
CONSTRAINT planet_pk PRIMARY KEY (id),
CONSTRAINT planet_check CHECK (LENGTH(name) > 1)
);

CREATE TABLE IF NOT EXISTS ticket (
id BIGINT AUTO_INCREMENT NOT NULL,
created_at TIMESTAMP WITH TIME ZONE NOT NULL,
client_id BIGINT NOT NULL,
from_planet_id VARCHAR(500) NOT NULL,
to_planet_id VARCHAR(500) NOT NULL,
CONSTRAINT ticket_pk PRIMARY KEY (id),
CONSTRAINT client_id_fk FOREIGN KEY (client_id) REFERENCES client(id) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT from_planet_id_fk FOREIGN KEY (from_planet_id) REFERENCES planet(id) ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT to_planet_id_fk FOREIGN KEY (to_planet_id) REFERENCES planet(id) ON DELETE CASCADE ON UPDATE CASCADE
);